//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimbradoAPI.Timbrado {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimbradoSoap", Namespace="http://ws.urbansa.com/")]
    public partial class Timbrado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TimbrarFOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbrarCPOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbrarN2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Timbrado() {
            this.Url = global::TimbradoAPI.Properties.Settings.Default.TimbradoAPI_Timbrado_Timbrado;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TimbrarFCompletedEventHandler TimbrarFCompleted;
        
        /// <remarks/>
        public event VerificarXMLCompletedEventHandler VerificarXMLCompleted;
        
        /// <remarks/>
        public event TimbrarCPCompletedEventHandler TimbrarCPCompleted;
        
        /// <remarks/>
        public event TimbrarN2CompletedEventHandler TimbrarN2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.urbansa.com/TimbrarF", RequestNamespace="http://ws.urbansa.com/", ResponseNamespace="http://ws.urbansa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TimbrarF(string Usuario, string Password, string StrXml) {
            object[] results = this.Invoke("TimbrarF", new object[] {
                        Usuario,
                        Password,
                        StrXml});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarFAsync(string Usuario, string Password, string StrXml) {
            this.TimbrarFAsync(Usuario, Password, StrXml, null);
        }
        
        /// <remarks/>
        public void TimbrarFAsync(string Usuario, string Password, string StrXml, object userState) {
            if ((this.TimbrarFOperationCompleted == null)) {
                this.TimbrarFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarFOperationCompleted);
            }
            this.InvokeAsync("TimbrarF", new object[] {
                        Usuario,
                        Password,
                        StrXml}, this.TimbrarFOperationCompleted, userState);
        }
        
        private void OnTimbrarFOperationCompleted(object arg) {
            if ((this.TimbrarFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarFCompleted(this, new TimbrarFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.urbansa.com/VerificarXML", RequestNamespace="http://ws.urbansa.com/", ResponseNamespace="http://ws.urbansa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificarXML(string Usuario, string Password, string StrXml) {
            object[] results = this.Invoke("VerificarXML", new object[] {
                        Usuario,
                        Password,
                        StrXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarXMLAsync(string Usuario, string Password, string StrXml) {
            this.VerificarXMLAsync(Usuario, Password, StrXml, null);
        }
        
        /// <remarks/>
        public void VerificarXMLAsync(string Usuario, string Password, string StrXml, object userState) {
            if ((this.VerificarXMLOperationCompleted == null)) {
                this.VerificarXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarXMLOperationCompleted);
            }
            this.InvokeAsync("VerificarXML", new object[] {
                        Usuario,
                        Password,
                        StrXml}, this.VerificarXMLOperationCompleted, userState);
        }
        
        private void OnVerificarXMLOperationCompleted(object arg) {
            if ((this.VerificarXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarXMLCompleted(this, new VerificarXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.urbansa.com/TimbrarCP", RequestNamespace="http://ws.urbansa.com/", ResponseNamespace="http://ws.urbansa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TimbrarCP(string Usuario, string Password, string Cadena) {
            object[] results = this.Invoke("TimbrarCP", new object[] {
                        Usuario,
                        Password,
                        Cadena});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarCPAsync(string Usuario, string Password, string Cadena) {
            this.TimbrarCPAsync(Usuario, Password, Cadena, null);
        }
        
        /// <remarks/>
        public void TimbrarCPAsync(string Usuario, string Password, string Cadena, object userState) {
            if ((this.TimbrarCPOperationCompleted == null)) {
                this.TimbrarCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarCPOperationCompleted);
            }
            this.InvokeAsync("TimbrarCP", new object[] {
                        Usuario,
                        Password,
                        Cadena}, this.TimbrarCPOperationCompleted, userState);
        }
        
        private void OnTimbrarCPOperationCompleted(object arg) {
            if ((this.TimbrarCPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarCPCompleted(this, new TimbrarCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.urbansa.com/TimbrarN2", RequestNamespace="http://ws.urbansa.com/", ResponseNamespace="http://ws.urbansa.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TimbrarN2(string Usuario, string Password, string Cadena) {
            object[] results = this.Invoke("TimbrarN2", new object[] {
                        Usuario,
                        Password,
                        Cadena});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarN2Async(string Usuario, string Password, string Cadena) {
            this.TimbrarN2Async(Usuario, Password, Cadena, null);
        }
        
        /// <remarks/>
        public void TimbrarN2Async(string Usuario, string Password, string Cadena, object userState) {
            if ((this.TimbrarN2OperationCompleted == null)) {
                this.TimbrarN2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarN2OperationCompleted);
            }
            this.InvokeAsync("TimbrarN2", new object[] {
                        Usuario,
                        Password,
                        Cadena}, this.TimbrarN2OperationCompleted, userState);
        }
        
        private void OnTimbrarN2OperationCompleted(object arg) {
            if ((this.TimbrarN2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarN2Completed(this, new TimbrarN2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TimbrarFCompletedEventHandler(object sender, TimbrarFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void VerificarXMLCompletedEventHandler(object sender, VerificarXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TimbrarCPCompletedEventHandler(object sender, TimbrarCPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void TimbrarN2CompletedEventHandler(object sender, TimbrarN2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarN2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarN2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591